server:
  port: 8081
  tomcat:
    threads:
      max: 200
spring:
  application:
    name: reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/demo
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false